parameters:
    monsieurbiz_sylius_media_manager.max_file_size.default: '%env(resolve:MONSIEURBIZ_SYLIUS_MEDIA_MANAGER_MAX_FILE_SIZE)%'
    monsieurbiz_sylius_media_manager.max_file_size.image: '%env(default:monsieurbiz_sylius_media_manager.max_file_size.default:resolve:MONSIEURBIZ_SYLIUS_MEDIA_MANAGER_MAX_FILE_SIZE_IMAGE)%'
    monsieurbiz_sylius_media_manager.max_file_size.audio: '%env(default:monsieurbiz_sylius_media_manager.max_file_size.default:resolve:MONSIEURBIZ_SYLIUS_MEDIA_MANAGER_MAX_FILE_SIZE_AUDIO)%'
    monsieurbiz_sylius_media_manager.max_file_size.video: '%env(default:monsieurbiz_sylius_media_manager.max_file_size.default:resolve:MONSIEURBIZ_SYLIUS_MEDIA_MANAGER_MAX_FILE_SIZE_VIDEO)%'
    monsieurbiz_sylius_media_manager.max_file_size.pdf: '%env(default:monsieurbiz_sylius_media_manager.max_file_size.default:resolve:MONSIEURBIZ_SYLIUS_MEDIA_MANAGER_MAX_FILE_SIZE_PDF)%'
    monsieurbiz_sylius_media_manager.max_file_size.favicon: '%env(default:monsieurbiz_sylius_media_manager.max_file_size.default:resolve:MONSIEURBIZ_SYLIUS_MEDIA_MANAGER_MAX_FILE_SIZE_FAVICON)%'
    monsieurbiz_sylius_media_manager.max_file_size.file: '%env(default:monsieurbiz_sylius_media_manager.max_file_size.default:resolve:MONSIEURBIZ_SYLIUS_MEDIA_MANAGER_MAX_FILE_SIZE_FILE)%'
    monsieurbiz_sylius_media_manager.liip_imagine.exclude_extensions:
        - 'svg'
        - 'ico'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    MonsieurBiz\SyliusMediaManagerPlugin\:
        resource: '../src/*'
        exclude: '../src/{Model}'

    # Decorator to allow us to have multiple data roots for svg images.
    MonsieurBiz\SyliusMediaManagerPlugin\Twig\Extension\FilterExtensionDecorator:
        decorates: 'liip_imagine.templating.filter_extension'
        arguments:
            $loaders: '%liip_imagine.loaders%'
            $publicDir: '%sylius_core.public_dir%'
            $excludeExtensions: '%monsieurbiz_sylius_media_manager.liip_imagine.exclude_extensions%'
