sylius_twig_hooks:
    hooks:
        sylius_admin.base#javascripts:
            media_manager_javascripts:
                template: '@MonsieurBizSyliusMediaManagerPlugin/admin/app.html.twig'
                priority: -200
